In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/archive (3).zip")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [ ]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [ ]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
score_columns= ['math score','reading score','writing score']
score_columns
['math score','reading score','writing score']
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
df[score_columns].mean()

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [ ]:
df[score_columns].median()

math score       66.0
reading score    70.0
writing score    69.0
dtype: float64

In [ ]:
df[score_columns].mode()

   math score  reading score  writing score
0          65             72             74

In [ ]:
df[score_columns].std()

math score       15.163080
reading score    14.600192
writing score    15.195657
dtype: float64

In [ ]:
df[score_columns].quantile(0.25)

math score       57.00
reading score    59.00
writing score    57.75
Name: 0.25, dtype: float64

In [ ]:
df[score_columns].quantile([0.5,0.75])

      math score  reading score  writing score
0.50        66.0           70.0           69.0
0.75        77.0           79.0           79.0

In [ ]:
df["Total Score"]=(df["math score"]+df["reading score"]+df["writing score"])
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score
0,Female,Group B,Bachelor'S Degree,Standard,none,72,72,74,218
1,Female,Group C,Some College,Standard,completed,69,90,88,247
2,Female,Group B,Master'S Degree,Standard,none,90,95,93,278
3,Male,Group A,Associate'S Degree,Free/Reduced,none,47,57,44,148
4,Male,Group C,Some College,Standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...
995,Female,Group E,Master'S Degree,Standard,completed,88,99,95,282
996,Male,Group C,High School,Free/Reduced,none,62,55,55,172
997,Female,Group C,High School,Free/Reduced,completed,59,71,65,195
998,Female,Group D,Some College,Standard,completed,68,78,77,223
999,Female,Group D,Some College,Free/Reduced,none,77,86,86,249

In [ ]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'Total Score'],
      dtype='object')

In [ ]:
df["Percentage"]=(df["Total Score"]/300)*100
df[["Total Score", "Percentage"]].head()

   Total Score  Percentage
0          218   72.666667
1          247   82.333333
2          278   92.666667
3          148   49.333333
4          229   76.333333

In [9]:
score_columns= ['math score','reading score','writing score']
for col in score_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print("\n", col)
    print("Lower Limit:", lower)
    print("Upper Limit:", upper)
    print("Number of Outliers:", len(outliers))

print("\nFinal Dataset:")
print(df.head())

 math score
Lower Limit: 27.0
Upper Limit: 107.0
Number of Outliers: 8

 reading score
Lower Limit: 29.0
Upper Limit: 109.0
Number of Outliers: 6

 writing score
Lower Limit: 25.875
Upper Limit: 110.875
Number of Outliers: 5

Final Dataset:
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score  \
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

   Total Score  Percentage
0          218   72.666667
1          247   82.333333
2          278   92.666667
3          148   49.333333
4          229   76.333333